version: "3"
services:
  lab1:
    build: .
    container_name: ucore_os_lab1
    volumes:
        - ${PWD}/os_kernel_lab:/lab
    working_dir: /lab/labcodes/lab1
    ports:
      - "1234:1234"
    command: bash -c "make clean && make && qemu-system-i386 -nographic -S -s -hda ./bin/ucore.img --serial stdio"